# Generated by Django 4.0.4 on 2022-06-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='products',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='products',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='emotions',
            field=models.ManyToManyField(null=True, to='store.emotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(null=True, to='store.genre'),
        ),
        migrations.AddField(
            model_name='product',
            name='instruments',
            field=models.ManyToManyField(null=True, to='store.instrument'),
        ),
    ]
