# Generated by Django 4.0.4 on 2022-06-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_emotion_products_remove_genre_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='emotions',
            field=models.ManyToManyField(blank=True, null=True, to='store.emotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='store.genre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='instruments',
            field=models.ManyToManyField(blank=True, null=True, to='store.instrument'),
        ),
    ]
