# Generated by Django 4.0.4 on 2022-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_composer_email_composer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='emotions',
            field=models.ManyToManyField(blank=True, to='store.emotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(blank=True, to='store.genre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='store.instrument'),
        ),
    ]
