# Generated by Django 4.0.4 on 2022-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_composer_image_customer_image_alter_emotion_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='composers/'),
        ),
        migrations.AlterField(
            model_name='composerorder',
            name='file',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emotions/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genres/'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instruments/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
