# Generated by Django 4.0.4 on 2022-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_composer_image_alter_composerorder_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composerorder',
            name='file',
            field=models.FileField(max_length=200, null=True, upload_to='../files/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(max_length=200, null=True, upload_to='../files/'),
        ),
    ]
