# Generated by Django 4.0.4 on 2022-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_composer_image_alter_composerorder_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
