# Generated by Django 4.0.4 on 2022-06-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_composer_email_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
