# Generated by Django 4.0.4 on 2022-06-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
