# Generated by Django 4.0.4 on 2022-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_composer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='composerorder',
            name='finish',
            field=models.BooleanField(max_length=200, null=True),
        ),
    ]
