# Generated by Django 4.0.4 on 2022-06-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_composerorder_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='composerorder',
            name='accept',
            field=models.BooleanField(max_length=200, null=True),
        ),
    ]
