# Generated by Django 4.0.4 on 2022-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_composer_confirm_composerorder_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='composerorder',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
