# Generated by Django 4.0.4 on 2022-06-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_feedback_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceorder',
            name='premium',
            field=models.BooleanField(max_length=200, null=True),
        ),
    ]
