# Generated by Django 4.0.4 on 2022-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_feedback_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
