# Generated by Django 4.0.4 on 2022-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_composer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
