# Generated by Django 4.0.4 on 2022-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_aiorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiorder',
            name='completed',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
