# Generated by Django 4.0.4 on 2022-06-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_aiorder_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiorder',
            name='audio_file',
            field=models.FileField(max_length=200, null=True, upload_to='files/'),
        ),
    ]
