# Generated by Django 4.0.4 on 2022-06-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_aiorder_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='font_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
