# Generated by Django 4.0.4 on 2022-06-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_aiorder_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='licence_file',
            field=models.FileField(max_length=200, null=True, upload_to='files/'),
        ),
    ]
