# Generated by Django 4.0.4 on 2022-06-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_aiorder_id_alter_composerorder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composerorder',
            name='license_file',
            field=models.FileField(max_length=200, null=True, upload_to='files/'),
        ),
    ]
