# Generated by Django 4.0.4 on 2022-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_composerorder_license_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiorder',
            name='license_file',
            field=models.FileField(max_length=200, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='aiorder',
            name='price',
            field=models.FloatField(default=5),
        ),
    ]
